Traceback (most recent call last):
  File "/root/bot-env/EchosDiscordBot/clean_log.py", line 17, in <module>
    with open(log_path, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/bot-env/EchosDiscordBot/bot.log'
✅ bot.log 清理完成：保留了近 3 天和 WARNING 以上等级日志
✅ bot.log 清理完成：保留了近 3 天和 WARNING 以上等级日志
✅ bot.log 清理完成：保留了近 3 天和 WARNING 以上等级日志
✅ [2025-07-01 18:51:04] bot.log 清理完成：保留了近 3 天和 WARNING 以上等级日志
✅ [2025-07-02 03:00:02] bot.log 清理完成：保留了近 3 天和 WARNING 以上等级日志
